import { Card } from "@/components/ui/Card";
import { MarkdownView } from "@/components/ui/MarkdownView";
import styles from "./GeneratedDossierPreview.module.css";

export function GeneratedDossierPreview({
  therapeuticArea,
  market,
  language,
  outputFormat,
  markdown,
}: {
  therapeuticArea: string;
  market: string;
  language: string;
  outputFormat: string;
  markdown: string;
}) {
  return (
    <Card className={styles.card}>
      <div className={styles.badge}>Draft generated by Claude</div>
      <h3 className={styles.title}>
        {therapeuticArea} Global Value Dossier — {market}
      </h3>
      <p className={styles.subline}>
        {language} · {outputFormat}
      </p>
      <div className={styles.body}>
        <MarkdownView markdown={markdown} />
      </div>
    </Card>
  );
}
