import type { LibraryDocument } from "../state/types";

export const mockDocuments: LibraryDocument[] = [
  {
    id: "doc-1",
    title: "EU MDR Technical Documentation — CE Mark Submission",
    type: "Technical Documentation",
    market: "EMA — European Union",
    language: "English",
    status: "Final",
    updatedAt: "2026-08-05T10:00:00.000Z",
    sizeBytes: 2_640_000,
    localizationGroupId: "eu-mdr-techdoc",
  },
  {
    id: "doc-2",
    title: "Documentation Technique MDR UE — Soumission Marquage CE",
    type: "Technical Documentation",
    market: "EMA — European Union",
    language: "French",
    status: "Final",
    updatedAt: "2026-08-05T10:00:00.000Z",
    sizeBytes: 2_710_000,
    localizationGroupId: "eu-mdr-techdoc",
  },
  {
    id: "doc-3",
    title: "MDR-Technische Dokumentation — CE-Kennzeichnung Einreichung",
    type: "Technical Documentation",
    market: "EMA — European Union",
    language: "German",
    status: "Final",
    updatedAt: "2026-08-05T10:00:00.000Z",
    sizeBytes: 2_690_000,
    localizationGroupId: "eu-mdr-techdoc",
  },
  {
    id: "doc-4",
    title: "FDA 510(k) Premarket Notification",
    type: "Premarket Notification",
    market: "FDA — United States",
    language: "English",
    status: "Completed",
    updatedAt: "2026-07-28T15:20:00.000Z",
    sizeBytes: 1_180_000,
  },
  {
    id: "doc-5",
    title: "Clinical Evaluation Report (CER)",
    type: "Clinical Evaluation Report",
    market: "EMA — European Union",
    language: "English",
    status: "Pending Review",
    updatedAt: "2026-08-11T09:10:00.000Z",
    sizeBytes: 3_120_000,
  },
  {
    id: "doc-6",
    title: "Risk Management File — ISO 14971",
    type: "Risk Management File",
    market: "Global",
    language: "English",
    status: "In Progress",
    updatedAt: "2026-08-12T08:00:00.000Z",
    sizeBytes: 940_000,
  },
  {
    id: "doc-7",
    title: "PMDA Shonin Application Summary",
    type: "Application Summary",
    market: "PMDA — Japan",
    language: "Japanese",
    status: "In Progress",
    updatedAt: "2026-08-06T12:40:00.000Z",
    sizeBytes: 1_760_000,
  },
  {
    id: "doc-8",
    title: "NMPA Registration Dossier — Chinese Instruction Manual",
    type: "Instruction Manual",
    market: "NMPA — China",
    language: "Chinese",
    status: "Pending Review",
    updatedAt: "2026-08-07T13:15:00.000Z",
    sizeBytes: 2_050_000,
  },
  {
    id: "doc-9",
    title: "Health Canada Product Monograph",
    type: "Product Monograph",
    market: "Health Canada",
    language: "English",
    status: "Completed",
    updatedAt: "2026-07-30T16:05:00.000Z",
    sizeBytes: 1_430_000,
  },
  {
    id: "doc-10",
    title: "TGA ARTG Application Summary",
    type: "Application Summary",
    market: "TGA — Australia",
    language: "English",
    status: "Final",
    updatedAt: "2026-07-22T11:30:00.000Z",
    sizeBytes: 1_275_000,
  },
];
