import { Card } from "@/components/ui/Card";
import { MarkdownView } from "@/components/ui/MarkdownView";
import type { MaterialType } from "@/lib/mock-data/msl-materials";
import styles from "./GeneratedMaterialPreview.module.css";

export function GeneratedMaterialPreview({
  material,
  tone,
  audience,
  focusArea,
  markdown,
}: {
  material: MaterialType;
  tone: string;
  audience: string;
  focusArea: string;
  markdown: string;
}) {
  return (
    <Card className={styles.card}>
      <div className={styles.badge}>Draft generated by Claude</div>
      <h3 className={styles.title}>{material.label}</h3>
      <p className={styles.subline}>
        {tone} · {audience} · {focusArea}
      </p>
      <div className={styles.body}>
        <MarkdownView markdown={markdown} />
      </div>
    </Card>
  );
}
